server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #opcional

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8089/eureka/'
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost


